version: "3"

services:

  nginx:
    image: nginx
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/etc/nginx/:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"